version: '3'

services:
  db:
    container_name: maramitas_db
    image: mysql:8.3
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  
  backend:
    container_name: maramitas_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  client:
    container_name: maramitas_client_build
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: pagespeed/nginx-pagespeed:latest
    ports:
      - 81:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

volumes:
  mysql_data:
