version: '3'

services:
  db:
    container_name: maramitas_db
    image: mysql:8.3
    restart: always
    volumes:
      - /var/docker-volumes/maramitas-app/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  
  backend:
    container_name: maramitas_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  #client:
  #  container_name: maramitas_client
  #  build: 
  #    context: ./client
  #    dockerfile: Dockerfile
  #  volumes:
  #    - ./client:/app
  #    - frontend-build:/app/build

  nginx:
    container_name: maramitas_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - staticfiles:/var/www/html/staticfiles
      - frontend-build:/var/www/html
    depends_on:
      - client
      - backend

volumes:
  staticfiles:
  frontend-build: