version: '3'

services:
  db:
    container_name: maramitas_db
    image: mysql:8.3
    restart: always
    volumes:
      - /var/docker-volumes/maramitas-app/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  
  backend:
    container_name: maramitas_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    container_name: maramitas_client
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    container_name: maramitas_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/index.html:/var/www/html/index.html
      - staticfiles:/var/www/html/staticfiles
    depends_on:
      - backend

volumes:
  staticfiles: